Repository scalameta/metals, pull requests merged in 2020-05, with the labels that each got.

#1611 Handle return to line in strings in OnTypeFormatting
  mtags/src/main/scala-2/scala/meta/internal/metals/MultilineStringFormattingProvider.scala
  tests/unit/src/test/scala/tests/OnTypeFormattingSuite.scala
Labels: feature

#1607 Don't ask .scalafmt.conf creation again
  metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
  metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
Labels: improvement

#1679 Improve code lens generation time
  metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
  metals/src/main/scala/scala/meta/internal/implementation/SuperMethodProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/codelenses/SuperMethodCodeLens.scala
Labels: improvement

#1684 Move additional settings to InitializationOptions
  metals/src/main/scala/scala/meta/internal/metals/ClientConfiguration.scala
  metals/src/main/scala/scala/meta/internal/metals/InitializationOptions.scala
Labels: improvement

#1677 Reworked Bloop connection and Tree View
  metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BspServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
  metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
  metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
  metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
  metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
  metals/src/main/scala/scala/meta/internal/tvp/TreeViewNode.scala
  metals/src/main/scala/scala/meta/internal/tvp/TreeViewProvider.scala
  tests/unit/src/main/scala/bill/Bill.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/BillLspSuite.scala
  tests/unit/src/test/scala/tests/TreeViewLspSuite.scala
Labels: improvement

#1625 Try to fix Debug Adapter Suites
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProtocol.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
  tests/unit/src/main/scala/tests/BaseDapSuite.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
  tests/unit/src/test/scala/tests/debug/BreakpointDapSuite.scala
  tests/unit/src/test/scala/tests/debug/StackFrameDapSuite.scala
  tests/unit/src/test/scala/tests/debug/StepDapSuite.scala
Labels: improvement

#1685 code action to make single string multiline with strip margin
  metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/codeactions/StringActions.scala
  tests/unit/src/test/scala/tests/codeactions/BaseCodeActionLspSuite.scala
  tests/unit/src/test/scala/tests/codeactions/StringActionsLspSuite.scala
Labels: feature

#1762 Keep modifiers when implementing abstract members
  mtags/src/main/scala-2/scala/meta/internal/pc/completions/OverrideCompletions.scala
  tests/cross/src/test/scala/tests/pc/AutoImplementAbstractMembersSuite.scala
Labels: bug, presentation-compiler

#1763 Support java files inside java modules for go to definition
  mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
  mtags/src/main/scala/scala/meta/internal/mtags/ClasspathLoader.scala
  tests/unit/src/test/scala/tests/JdkSourcesSuite.scala
Labels: bug

#1538 Add early support for Ammonite scripts
  build.sbt
  metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BspServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
  metals/src/main/scala/scala/meta/internal/metals/CancelableFuture.scala
  metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
  metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
  metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
  metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
  metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala
  metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/MutableCancelable.scala
  metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
  metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
  mtags/src/main/scala-2/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
  mtags/src/main/scala-2/scala/meta/internal/pc/AutoImports.scala
  mtags/src/main/scala/scala/meta/internal/metals/CompilerOffsetParams.scala
  mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
  tests/cross/src/test/scala/tests/pc/AutoImportsSuite.scala
  tests/slow/src/test/scala/tests/feature/AmmoniteSuite.scala
  tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
  tests/unit/src/main/scala/tests/TestingClient.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/AmmoniteSuite.scala
  tests/unit/src/test/scala/tests/UnsupportedDebuggingLspSuite.scala
Labels: feature

#1758 Handle workspaces with multiple build files.
  metals/src/main/resources/db/migration/V1__Create_tables.sql
  metals/src/main/scala/scala/meta/internal/builds/BuildTools.scala
  metals/src/main/scala/scala/meta/internal/metals/BloopInstall.scala
  metals/src/main/scala/scala/meta/internal/metals/ChosenBuildTool.scala
  metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/Tables.scala
  tests/slow/src/test/scala/tests/MultipleBuildFilesLspSuite.scala
  tests/unit/src/main/scala/tests/TestingClient.scala
  tests/unit/src/test/scala/tests/ChosenBuildToolSuite.scala
  tests/unit/src/test/scala/tests/DetectionSuite.scala
Labels: improvement
