Repository scalameta/metals, pull requests merged in 2020-08, with the labels that each got.

#1968 Bump recommended scalafmt version and local scalafmt version to 2.6.4
  .scalafmt.conf
  bin/scalafmt
  build.sbt
  metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
  tests/unit/src/test/scala/tests/NewProjectLspSuite.scala
Labels: improvement

#1967 Change implicits to Dotty syntax.
  .scalafmt.conf
  mtags/src/main/scala-0.24/scala/meta/internal/metals/ClassFinder.scala
  mtags/src/main/scala-0.24/scala/meta/internal/pc/Symbols.scala
  mtags/src/main/scala-0.25/scala/meta/internal/metals/ClassFinder.scala
  mtags/src/main/scala-0.25/scala/meta/internal/pc/Symbols.scala
  mtags/src/main/scala-0.26/scala/meta/internal/metals/ClassFinder.scala
  mtags/src/main/scala-0.26/scala/meta/internal/pc/Symbols.scala
  mtags/src/main/scala-3/scala/meta/internal/pc/Scala3CompilerAccess.scala
  mtags/src/main/scala-3/scala/meta/internal/pc/ScalaPresentationCompiler.scala
  mtags/src/main/scala-3/scala/meta/internal/pc/SymbolPrinter.scala
Labels: Scala 3, improvement, up for debate

#1949 Fix `filterText` value for completion item in string interpolation
  mtags/src/main/scala-2/scala/meta/internal/pc/completions/InterpolatorCompletions.scala
  tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
Labels: bug

#1865 Sbt support - multiply bsp connections
  build.sbt
  metals/src/main/scala/scala/meta/internal/builds/SbtBuildTool.scala
  metals/src/main/scala/scala/meta/internal/metals/AdjustLspData.scala
  metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BspConnector.scala
  metals/src/main/scala/scala/meta/internal/metals/BspServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BspSession.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
  metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
  metals/src/main/scala/scala/meta/internal/metals/Compilers.scala
  metals/src/main/scala/scala/meta/internal/metals/FileSystemSemanticdbs.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsEnrichments.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
  metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
  mtags/src/main/scala-2/scala/meta/internal/pc/MetalsGlobal.scala
  mtags/src/main/scala/scala/meta/internal/mtags/CommonMtagsEnrichments.scala
  tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala
  tests/unit/src/main/scala/tests/BaseLspSuite.scala
  tests/unit/src/main/scala/tests/QuickBuild.scala
  tests/unit/src/main/scala/tests/ScriptsAssertions.scala
  tests/unit/src/main/scala/tests/TestingDiagnostics.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/main/scala/tests/TestingWorkspaceSymbolProvider.scala
  tests/unit/src/test/scala/tests/BuildServerConnectionLspSuite.scala
Labels: feature
