Repository scalameta/metals, pull requests merged in 2020-04, with the labels that each got.

#1576 Add in ... to signifigy truncation in worksheets
  metals/src/main/scala/scala/meta/internal/worksheets/DecorationWorksheetPublisher.scala
  metals/src/main/scala/scala/meta/internal/worksheets/MdocEnrichments.scala
  metals/src/main/scala/scala/meta/internal/worksheets/WorkspaceEditWorksheetPublisher.scala
  tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
Labels: improvement

#1466 'StartDebugAdapter' command now accepts user's parameters (launch.json)
  metals/src/main/scala/scala/meta/internal/metals/BatchedFunction.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargetClasses.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargetClassesFinder.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildTargets.scala
  metals/src/main/scala/scala/meta/internal/metals/JsonParser.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProxy.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugServer.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
Labels: feature

#1598 goto Implementations with local alias types
  metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
  tests/unit/src/test/scala/tests/ImplementationLspSuite.scala
Labels: bug

#1606 Properly set the arguments field in sever commands documentation
  metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
Labels: documentation

#1659 Add support for Scala 2.13.2
  build.sbt
  metals/src/main/scala/scala/meta/internal/pantsbuild/BloopPants.scala
  mtags/src/main/scala-2/scala/meta/internal/pc/ScalaPresentationCompiler.scala
  mtags/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolQuery.scala
  tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
  tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
  tests/cross/src/test/scala/tests/pc/SignatureHelpDocSuite.scala
  tests/slow/src/test/scala/tests/feature/CompletionCrossLspSuite.scala
  tests/unit/src/main/scala/tests/BaseWorksheetLspSuite.scala
  tests/unit/src/main/scala/tests/QuickBuild.scala
  tests/unit/src/test/scala/tests/MessagesSuite.scala
Labels: feature

#1637 Use DefinitionProvider instead of index in RenameProvider
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
  tests/slow/src/test/scala/tests/feature/RenameCrossLspSuite.scala
  tests/unit/src/main/scala/tests/BaseRenameLspSuite.scala
  tests/unit/src/test/scala/tests/RenameLspSuite.scala
Labels: improvement

#1658 Make sure that the workspace contains no errors when running
  metals/src/main/scala/scala/meta/internal/metals/BuildTargetClassesFinder.scala
  metals/src/main/scala/scala/meta/internal/metals/ForwardingMetalsBuildClient.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsBuildClient.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala
  tests/unit/src/test/scala/tests/DebugProtocolSuite.scala
Labels: bug
