Repository scalameta/metals, pull requests merged in 2020-03, with the labels that each got.

#1543 Update sbt-munit plugin
  project/plugins.sbt
Labels: tech debt

#1545 Update scalameta dependency
  build.sbt
Labels: tech debt

#1544 Update mdoc dependencies
  build.sbt
  project/plugins.sbt
Labels: tech debt

#1526 Sort references before returning them
  metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
  tests/mtest/src/main/scala/tests/Assertions.scala
  tests/unit/src/main/scala/tests/BaseRangesSuite.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/ImplementationLspSuite.scala
  tests/unit/src/test/scala/tests/ReferenceLspSuite.scala
Labels: improvement

#1547 Add support to query remote language server as fallback.
  build.sbt
  docs/contributors/remote-language-server.md
  metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/DefinitionResult.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsHttpServer.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsServerConfig.scala
  metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
  metals/src/main/scala/scala/meta/internal/remotels/RemoteLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/remotels/RemoteLocationResult.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/remotels/RemoteLanguageServerLspSuite.scala
  tests/unit/src/test/scala/tests/remotels/TestingRemoteLanguageServer.scala
  website/sidebars.json
Labels: feature

#1554 Dependency updates
  build.sbt
Labels: tech debt

#1555 A few more dependency updates
  build.sbt
Labels: tech debt

#1557 Update coursier dependencies
  build.sbt
Labels: tech debt

#1556 Update lsp4j-debug
  build.sbt
  metals/src/main/scala/scala/meta/internal/metals/debug/SetBreakpointsRequestHandler.scala
  tests/unit/src/main/scala/scala/meta/internal/metals/debug/DebuggeeBreakpoints.scala
  tests/unit/src/main/scala/scala/meta/internal/metals/debug/Debugger.scala
  tests/unit/src/main/scala/tests/DapTestEnrichments.scala
Labels: tech debt

#1561 Remove deprecations
  metals/src/main/scala/scala/meta/internal/implementation/Supermethods.scala
  metals/src/main/scala/scala/meta/internal/metals/InteractiveSemanticdbs.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/NewFilesProvider.scala
  metals/src/main/scala/scala/meta/internal/pantsbuild/Graph.scala
  metals/src/main/scala/scala/meta/internal/worksheets/WorkspaceEditWorksheetPublisher.scala
  mtags/src/main/scala/scala/meta/internal/mtags/ScalaMtags.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
Labels: tech debt

#1549 Fix recommendations for Scala versions and add better messages.
  metals/src/main/scala/scala/meta/internal/metals/Doctor.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/ScalaTarget.scala
  metals/src/main/scala/scala/meta/internal/metals/ScalaVersions.scala
  mtags/src/main/scala/scala/meta/internal/semver/SemVer.scala
  tests/slow/src/test/scala/tests/sbt/SbtLspSuite.scala
  tests/unit/src/test/scala/tests/BillLspSuite.scala
  tests/unit/src/test/scala/tests/MessagesSuite.scala
  tests/unit/src/test/scala/tests/ScalaVersionsSuite.scala
  tests/unit/src/test/scala/tests/WarningsLspSuite.scala
Labels: bug

#1531 Small clean-ups
  metals/src/main/scala/scala/meta/internal/metals/BloopServers.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
  metals/src/main/scala/scala/meta/internal/metals/CodeActionProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/Compilations.scala
  metals/src/main/scala/scala/meta/internal/metals/DefinitionProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/FormattingProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/MultilineStringFormattingProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/ReferenceProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/SemanticdbIndexer.scala
  metals/src/main/scala/scala/meta/internal/metals/StatusBar.scala
  metals/src/main/scala/scala/meta/internal/metals/WorkspaceSearchVisitor.scala
  metals/src/main/scala/scala/meta/internal/metals/WorkspaceSymbolProvider.scala
  metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
  metals/src/main/scala/scala/meta/internal/tvp/MetalsTreeViewProvider.scala
  metals/src/main/scala/scala/meta/internal/tvp/TreeViewProvider.scala
  mtags/src/main/scala/scala/meta/internal/mtags/OnDemandSymbolIndex.scala
Labels: improvement, tech debt
