Repository scalameta/metals, pull requests merged in 2022-08, with the labels that each got.

#4231 feat: include anon classes (val x = new Trait {}) in 'find all implementations'
  metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
  tests/unit/src/test/scala/tests/ImplementationLspSuite.scala
Labels: improvement

#4221 chore(ci): migrate to actions/java to use built-in sbt caching
  .github/workflows/ci.yml
  .github/workflows/mtags-auto-release.yml
  .github/workflows/release.yml
  tests/unit/src/test/scala/tests/FindTextInDependencyJarsSuite.scala
  tests/unit/src/test/scala/tests/WorkspaceSymbolLspSuite.scala
Labels: merge after release

#3790 Add better Scala CLI support
  build.sbt
  metals/src/main/scala/scala/meta/internal/bsp/MetalsBspException.scala
  metals/src/main/scala/scala/meta/internal/builds/ShellRunner.scala
  metals/src/main/scala/scala/meta/internal/implementation/ImplementationProvider.scala
  metals/src/main/scala/scala/meta/internal/metals/BuildServerConnection.scala
  metals/src/main/scala/scala/meta/internal/metals/Diagnostics.scala
  metals/src/main/scala/scala/meta/internal/metals/DismissedNotifications.scala
  metals/src/main/scala/scala/meta/internal/metals/ImportedBuild.scala
  metals/src/main/scala/scala/meta/internal/metals/Indexer.scala
  metals/src/main/scala/scala/meta/internal/metals/JavaInteractiveSemanticdb.scala
  metals/src/main/scala/scala/meta/internal/metals/Messages.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsBuildServer.scala
  metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala
  metals/src/main/scala/scala/meta/internal/metals/ServerCommands.scala
  metals/src/main/scala/scala/meta/internal/metals/UserConfiguration.scala
  metals/src/main/scala/scala/meta/internal/metals/ammonite/Ammonite.scala
  metals/src/main/scala/scala/meta/internal/metals/scalacli/ScalaCli.scala
  metals/src/main/scala/scala/meta/internal/process/SystemProcess.scala
  metals/src/main/scala/scala/meta/internal/rename/RenameProvider.scala
  project/V.scala
  tests/unit/src/main/scala/tests/BaseAmmoniteSuite.scala
  tests/unit/src/main/scala/tests/BaseRangesSuite.scala
  tests/unit/src/main/scala/tests/BaseScalaCliSuite.scala
  tests/unit/src/main/scala/tests/FileLayout.scala
  tests/unit/src/main/scala/tests/TestingClient.scala
  tests/unit/src/main/scala/tests/TestingServer.scala
  tests/unit/src/test/scala/tests/JdkVersionSuite.scala
  tests/unit/src/test/scala/tests/ScalaCliSuite.scala
  tests/unit/src/test/scala/tests/SystemProcessSuite.scala
  tests/unit/src/test/scala/tests/troubleshoot/ProblemResolverSuite.scala
Labels: affects clients, merge after release

#4237 Revert "[Scala 3] Revert type completions feature (#4236)"
  mtags/src/main/scala-2/scala/meta/internal/pc/AutoImportsProvider.scala
  mtags/src/main/scala-3/scala/meta/internal/pc/completions/Completions.scala
  tests/cross/src/test/scala/tests/pc/CompletionDocSuite.scala
  tests/cross/src/test/scala/tests/pc/CompletionInterpolatorSuite.scala
  tests/cross/src/test/scala/tests/pc/CompletionSnippetSuite.scala
  tests/cross/src/test/scala/tests/pc/CompletionSuite.scala
  tests/cross/src/test/scala/tests/pc/CompletionWorkspaceSuite.scala
  tests/unit/src/main/scala/tests/BaseCompletionLspSuite.scala
Labels: merge after release
